# This is a basic workflow to help you get started with Actions

name: FTP-Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Setup NodeJs Environment
      uses: actions/setup-node@v2.4.0
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: premium66.web-hosting.com
        username: advaaxrv
        password: ${{ secrets.DEPLOY_FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /advaaxrv/jaapps.com/apps/assetlog/

